name: multistreaming
services:
  camera:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
      - ./worker.php:/app/worker.php
      - ./vendor:/opt/cache/vendor/
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
