name: multistreaming
services:
  camera:
    build:
      context: .
      target: prod
    ports:
      - 80:80
    container_name: camera
    restart: unless-stopped
    volumes:
      - ./example-config.json:/app/config.json
    environment:
      - TYPE=file
      - CONFIG=/app/config.json
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
  redis:
    image: redis:latest
    restart: always
    container_name: redis
