name: multistreaming
services:
  camera:
    build:
      context: .
      target: prod
    restart: unless-stopped
    depends_on:
      - stream-server
    volumes:
      - ./example-config.json:/app/config.json
      - stream:/app/resources
    environment:
      - TYPE=remote_file
      - CONFIG=${AGENT_DSN}streams/${API_KEY}
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
      - STREAM_HOST=stream-server
      - API_KEY=${API_KEY}
      - AGENT_DSN=${AGENT_DSN}
      - SNAPSHOT_DIR=/app/resources
  stream-server:
    image: ossrs/srs:6
    hostname: stream-server
    volumes:
      - ./docker/srs/rtsp.conf:/usr/local/srs/conf/rtsp.conf
      - stream:/usr/local/srs/objs/nginx/html/snapshot/
    entrypoint: [ "./objs/srs","-c","conf/rtsp.conf" ]
  redis:
    image: redis:latest
    restart: always
volumes:
  stream:
